support WASD along with arrow keys
fabioarnold/zeroman pull request #3
Opened 2022-11-02 15:11 UTC by marler8997

2022-11-02 21:32 UTC, fabioarnold requested changes
In a completely separate part of the code (I know, sorry) the S key is already used to save snapshots of the game state: https://github.com/fabioarnold/zeroman/blob/6d74bbe85c836c24e486eb3807a4722dcec31e88/src/main.zig#L320

Maybe bind snapshot saving to a different key (combination?). I don't have a good idea for that. Ctrl+S is sadly already used by the browser. And I don't like F-keys since they're not easily accessible on my keyboard. Maybe use 1 & 2 for saving and loading?

2022-11-03 03:27 UTC, marler8997 commented
1/2 for Save/Load seems reasonable to me, pushed a commit with this change.

2022-11-03 07:45 UTC, fabioarnold approved these changes

2022-11-03 07:45 UTC, merged

2022-11-03 07:45 UTC, fabioarnold commented
Thank you!